/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcp.client.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import model.Match;
import model.ObjectWrapper;
import model.Player;
import model.Round;
import tcp.client.control.TCPClientCtr;

/**
 *
 * @author Admin
 */
public class InvitePlayDialog extends javax.swing.JDialog {
    private final ArrayList<Player> listInvitePlay;
    private HomeFrm home;

    
    /**
     * Creates new form InvitePlayDialog
     */
    public InvitePlayDialog(java.awt.Frame parent, boolean modal) {
        super(parent, "Moi thi dau", modal);
        home = (HomeFrm) parent;
        initComponents();
        listInvitePlay = new ArrayList<>();
        jListInvitePlay.setModel(new DefaultListModel<>());
        
        lblName.setText(home.getPlayer().toString());
    }
    
    public ArrayList<Player> getListInvitePlay() {
        return listInvitePlay;
    }

    public void addInvite(Player invitedPlayer) {
        listInvitePlay.add(invitedPlayer);
//        ((DefaultListModel) jListInvitePlay.getModel())
//                .addElement(getPlayerSimpleInformation(invitedPlayer));
        DefaultListModel model = (DefaultListModel) jListInvitePlay.getModel();
        model.addElement(invitedPlayer.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListInvitePlay = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        lblName.setText("_name_");

        jListInvitePlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListInvitePlayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListInvitePlay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListInvitePlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListInvitePlayMouseClicked
        // TODO add your handling code here:
        JList list = (JList) evt.getSource();
        int index = list.locationToIndex(evt.getPoint());
        Player frq = listInvitePlay.get(index);
        String message = "Bạn muốn chơi với " + frq.toString() + " không?";
        int dialogResult = JOptionPane.showConfirmDialog(this, message, "", JOptionPane.YES_NO_CANCEL_OPTION);
        
        TCPClientCtr myControl = home.getMyControl();
        Player player = home.getPlayer();
        
        if(dialogResult == JOptionPane.YES_OPTION) {
            Match m = new Match(player, frq);
            Round round = new Round();
            round.setId(1);
            m.setRound(round);
            
            myControl.sendData(new ObjectWrapper(ObjectWrapper.REPLY_INVITE_PLAY, new Object[]{"accept", m}));
            listInvitePlay.removeAll(listInvitePlay);
            ((DefaultListModel) jListInvitePlay.getModel()).removeAllElements();
            MatchFrm matchDialog = new MatchFrm(home, m);
            matchDialog.setVisible(true);
            setVisible(false);
        }else if (dialogResult == JOptionPane.NO_OPTION) {
            myControl.sendData(new ObjectWrapper(ObjectWrapper.REPLY_INVITE_PLAY, new Object[]{"deny", player, frq}));
            listInvitePlay.remove(index);
            ((DefaultListModel) jListInvitePlay.getModel()).remove(index);
        }
    }//GEN-LAST:event_jListInvitePlayMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListInvitePlay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
